language: cpp
script:
compiler: gcc
dist: trusty
 
before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
 
install: 
  - sudo apt-get install libnetfilter-conntrack-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install libssl-dev libtins-dev libipset-dev
  - sudo apt-get install openssl libcurl libtins
  - sudo apt-get install ca-certificates 
  # Not needed for tests: ipset iptables-persistent brotli wget
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
 
script: 
  - cd src
  - cmake .
  - make 
  - make test
