version: 2
jobs:
  build:
    docker:
      image: ubuntu:xenial
    steps:
      -run: 
        command: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update -qq
          sudo apt-get install libnetfilter-conntrack-de
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install -qq g++-5
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
      - checkout
      - run: |
        cmake -DCMAKE_BUILD_TYPE=Debug  .
        make -j4
        make test
